[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["Alexander Hultnér <ahultner@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest-xdist = "^1.30.0"
pytest-cov = "^2.8.1"
pytest-tldr = "^0.2.1"
toolz = "^0.10.0"
more_itertools = "^8.0.2"
bpython = "^0.18"
hypothesis = "^4.56.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
